# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
